Sprint 3
ClevertecFrontendLab/AntonFartovii pull request #3
Opened 2024-03-04 08:00 UTC by AntonFartovii

2024-03-04 08:02 UTC, ValadzkoAliaksei commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 5.
Количество непройденных тестов: 0.
***
**empty-review-list.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/AntonFartovii/1709539368/empty-review-list.png)
***
**expand-review-list.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/AntonFartovii/1709539368/expand-review-list.png)
***
**get-feedback-error.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/AntonFartovii/1709539368/get-feedback-error.png)
***
**more-than-4-reviews.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/AntonFartovii/1709539368/more-than-4-reviews.png)
***
**one-review.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/AntonFartovii/1709539368/one-review.png)
***
**review-modal.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/AntonFartovii/1709539368/review-modal.png)
***
**reviews-not-saved-modal.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/AntonFartovii/1709539368/reviews-not-saved-modal.png)
***
**updated-review-list.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/AntonFartovii/1709539368/updated-review-list.png)

2024-03-04 08:16 UTC, SergeyGlazun requested changes
<img width="848" alt="image" src="https://github.com/ClevertecFrontendLab/AntonFartovii/assets/70904466/747adcdc-a5c6-4647-9a31-8344629efad9">
не хватает уведомления, запускайте тесты локально в Electron он наиболее точно определяет косяки, так вам удобнее будет самих себя проверять

2024-03-04 08:17 UTC, SergeyGlazun commented
<img width="552" alt="image" src="https://github.com/ClevertecFrontendLab/AntonFartovii/assets/70904466/abe9dd92-c810-4bac-8742-b79ababb2882">
не хватает текста и на макете с боку штучка такая должна быть

2024-03-04 20:04 UTC, ValadzkoAliaksei commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 5.
Количество непройденных тестов: 0.
***
**empty-review-list.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/AntonFartovii/1709582686/empty-review-list.png)
***
**expand-review-list.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/AntonFartovii/1709582686/expand-review-list.png)
***
**get-feedback-error.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/AntonFartovii/1709582686/get-feedback-error.png)
***
**more-than-4-reviews.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/AntonFartovii/1709582686/more-than-4-reviews.png)
***
**one-review.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/AntonFartovii/1709582686/one-review.png)
***
**review-modal.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/AntonFartovii/1709582686/review-modal.png)
***
**reviews-not-saved-modal.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/AntonFartovii/1709582686/reviews-not-saved-modal.png)
***
**updated-review-list.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/AntonFartovii/1709582686/updated-review-list.png)

2024-03-04 20:07 UTC, AntonFartovii commented
Прошёл по всем замечаниям - всё поправил.

2024-03-04 22:26 UTC, SergeyGlazun approved these changes

2024-03-05 12:55 UTC, AntonFartovii commented
Добавил требуемые зависимотсти в useEffect

2024-03-05 16:13 UTC, merged